# Generated by Django 3.0.7 on 2022-03-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_auto_20220317_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_slug',
        ),
    ]
